Here, I have trained my first neural network using PyTorch on a cancer dataset. This code is written from basic principles, without using any high-level libraries like Autograd, NN module, optimizers, or data loaders which we will explore later. 

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [ ]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
241        12.42         15.04           78.61      476.5          0.07926   
207        17.01         20.26          109.70      904.3          0.08772   
519        12.75         16.70           82.51      493.8          0.11250   
172        15.46         11.89          102.50      736.9          0.12570   
366        20.20         26.83          133.70     1234.0          0.09905   
..           ...           ...             ...        ...              ...   
283        16.24         18.77          108.80      805.1          0.10660   
142        11.43         17.31           73.66      398.0          0.10920   
50         11.76         21.60           74.72      427.9          0.08637   
460        17.08         27.15          111.20      930.9          0.09898   
302        20.09         23.86          134.70     1247.0          0.10800   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
241           0.03393         0.01053              0.01108         0.1546   
207           0.07304         0.06950              0.05390         0.2026   
519           0.11170         0.03880              0.02995         0.2120   
172           0.15550         0.20320              0.10970         0.1966   
366           0.16690         0.16410              0.12650         0.1875   
..                ...             ...                  ...            ...   
283           0.18020         0.19480              0.09052         0.1876   
142           0.09486         0.02031              0.01861         0.1645   
50            0.04966         0.01657              0.01115         0.1495   
460           0.11100         0.10070              0.06431         0.1793   
302           0.18380         0.22830              0.12800         0.2249   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
241                 0.05754  ...         13.20          20.37   
207                 0.05223  ...         19.80          25.05   
519                 0.06623  ...         14.45          21.74   
172                 0.07069  ...         18.79          17.04   
366                 0.06020  ...         24.19          33.81   
..                      ...  ...           ...            ...   
283                 0.06684  ...         18.55          25.09   
142                 0.06562  ...         12.78          26.76   
50                  0.05888  ...         12.98          25.72   
460                 0.06281  ...         22.96          34.49   
302                 0.07469  ...         23.68          29.43   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
241            83.85       543.4            0.1037            0.07776   
207           130.00      1210.0            0.1111            0.14860   
519            93.63       624.1            0.1475            0.19790   
172           125.00      1102.0            0.1531            0.35830   
366           160.00      1671.0            0.1278            0.34160   
..               ...         ...               ...                ...   
283           126.90      1031.0            0.1365            0.47060   
142            82.66       503.0            0.1413            0.17920   
50             82.98       516.5            0.1085            0.08615   
460           152.10      1648.0            0.1600            0.24440   
302           158.80      1696.0            0.1347            0.33910   

     concavity_worst  concave points_worst  symmetry_worst  \
241          0.06243               0.04052          0.2901   
207          0.19320               0.10960          0.3275   
519          0.14230               0.08045          0.3071   
172          0.58300               0.18270          0.3216   
366          0.37030               0.21520          0.3271   
..               ...                   ...             ...   
283          0.50260               0.17320         

In [ ]:
y_train

241    B
207    M
519    B
172    M
366    M
      ..
283    M
142    B
50     B
460    M
302    M
Name: diagnosis, Length: 455, dtype: object

### Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.5356948 , -0.99180368, -0.6005322 , ..., -1.19250232,
         0.00578779, -0.88965327],
       [ 0.77446364,  0.22603082,  0.68794316, ..., -0.11176926,
         0.64867773, -1.0629525 ],
       [-0.4415004 , -0.60452297, -0.43890293, ..., -0.56781108,
         0.29801049,  0.0894322 ],
       ...,
       [-0.72408359,  0.538655  , -0.76174703, ..., -1.24522482,
        -0.79868412, -1.01107311],
       [ 0.79444427,  1.83347904,  0.75010827, ...,  0.60632059,
         0.19315411,  0.36704212],
       [ 1.65361134,  1.06591668,  1.72402821, ...,  1.18204405,
         0.68133791,  0.59277265]])

In [ ]:
y_train

241    B
207    M
519    B
172    M
366    M
      ..
283    M
142    B
50     B
460    M
302    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

### Defining the Model

In [ ]:
class MyNN():

  def  __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    eplsilon = 1e-7;
    y_pred = torch.clamp(y_pred, eplsilon, 1-eplsilon)

    # Calculate loss
    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
    return loss.mean()

### Important Parameters


In [ ]:
learning_rate = 0.1
epochs = 1000

### Training Pipeline


In [ ]:
# create model
model = MyNN(X_train_tensor)

for epoch in range(epochs):

  # Forward Bias
  y_pred = model.forward(X_train_tensor)

  # Loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.554744486856361
Epoch: 2, Loss: 3.3812559336839647
Epoch: 3, Loss: 3.19980135388725
Epoch: 4, Loss: 3.0136973490829915
Epoch: 5, Loss: 2.825035465342804
Epoch: 6, Loss: 2.6329739846574753
Epoch: 7, Loss: 2.4385729563078056
Epoch: 8, Loss: 2.240820266163764
Epoch: 9, Loss: 2.0249742172144596
Epoch: 10, Loss: 1.8149953357326536
Epoch: 11, Loss: 1.6149023248466867
Epoch: 12, Loss: 1.4263013446163502
Epoch: 13, Loss: 1.2564573757071902
Epoch: 14, Loss: 1.1130254514241233
Epoch: 15, Loss: 0.9979579782135812
Epoch: 16, Loss: 0.9106879294148471
Epoch: 17, Loss: 0.8479225955432976
Epoch: 18, Loss: 0.8045674471486626
Epoch: 19, Loss: 0.7752242077056949
Epoch: 20, Loss: 0.7553318402022959
Epoch: 21, Loss: 0.7415524172434685
Epoch: 22, Loss: 0.7316658075122593
Epoch: 23, Loss: 0.7242944736349349
Epoch: 24, Loss: 0.7186079338844396
Epoch: 25, Loss: 0.7140968407759618
Epoch: 26, Loss: 0.710435067551598
Epoch: 27, Loss: 0.7074039108727944
Epoch: 28, Loss: 0.7048510732709901
Epoch: 

In [ ]:
model.bias

tensor([-0.4334], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor) # This will give the values of y_pred from 0 to 1
  y_pred = (y_pred >0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')