In [60]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [61]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [62]:
df.shape

(569, 33)

In [63]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [65]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
84        12.000         15.65           76.95      443.3          0.09723   
95        20.260         23.03          132.40     1264.0          0.09078   
35        16.740         21.59          110.10      869.5          0.09610   
260       20.310         27.06          132.90     1288.0          0.10000   
536       14.270         22.55           93.77      629.8          0.10380   
..           ...           ...             ...        ...              ...   
89        14.640         15.24           95.77      651.9          0.11320   
335       17.060         21.00          111.80      918.6          0.11190   
218       19.800         21.56          129.70     1230.0          0.09383   
412        9.397         21.68           59.75      268.8          0.07969   
93        13.450         18.30           86.60      555.1          0.10220   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
84            0.07165         0.04151             0.018630         0.2079   
95            0.13130         0.14650             0.086830         0.2095   
35            0.13360         0.13480             0.060180         0.1896   
260           0.10880         0.15190             0.093330         0.1814   
536           0.11540         0.14630             0.061390         0.1926   
..                ...             ...                  ...            ...   
89            0.13390         0.09966             0.070640         0.2116   
335           0.10560         0.15080             0.099340         0.1727   
218           0.13060         0.12720             0.086910         0.2094   
412           0.06053         0.03735             0.005128         0.1274   
93            0.08165         0.03974             0.027800         0.1638   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
84                  0.05968  ...        13.670          24.90   
95                  0.05649  ...        24.220          31.59   
35                  0.05656  ...        20.010          29.02   
260                 0.05572  ...        24.330          39.16   
536                 0.05982  ...        15.290          34.27   
..                      ...  ...           ...            ...   
89                  0.06346  ...        16.340          18.24   
335                 0.06071  ...        20.990          33.15   
218                 0.05581  ...        25.730          28.64   
412                 0.06724  ...         9.965          27.99   
93                  0.05710  ...        15.100          25.94   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
84             87.78       567.9            0.1377             0.2003   
95            156.10      1750.0            0.1190             0.3539   
35            133.50      1229.0            0.1563             0.3835   
260           162.30      1844.0            0.1522             0.2945   
536           104.30       728.3            0.1380             0.2733   
..               ...         ...               ...                ...   
89            109.40       803.6            0.1277             0.3089   
335           143.20      1362.0            0.1449             0.2053   
218           170.30      2009.0            0.1353             0.3235   
412            66.61       301.0            0.1086             0.1887   
93             97.59       699.4            0.1339             0.1751   

     concavity_worst  concave points_worst  symmetry_worst  \
84            0.2267               0.07632          0.3379   
95            0.4098               0.15730          0.3689   
35            0.5409               0.18130          0.4863   
260           0.3788               0.16970          0.3151   
536           0.4234               0.13620          0.2698   
..               ...                   ...             ...   
89            0.2604               0.13970         

In [66]:
y_train

84     B
95     M
35     M
260    M
536    M
      ..
89     B
335    M
218    M
412    B
93     B
Name: diagnosis, Length: 455, dtype: object

## Scaling

In [67]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [68]:
X_train

array([[-0.61621825, -0.85155578, -0.63230687, ..., -0.59834846,
         0.74805978, -0.27416462],
       [ 1.71099949,  0.87175577,  1.63070187, ...,  0.62825904,
         1.23568511, -0.03964796],
       [ 0.71925537,  0.53549986,  0.72060097, ...,  0.99178806,
         3.08236943,  0.10032256],
       ...,
       [ 1.58139656,  0.52849453,  1.52051028, ...,  1.00239099,
         0.26200743, -0.09933351],
       [-1.34960176,  0.55651585, -1.33426811, ..., -1.36600057,
        -0.82964411,  0.40297581],
       [-0.20768729, -0.2327515 , -0.23847397, ..., -0.55608821,
        -0.35460266, -0.97190449]])

In [69]:
y_train

84     B
95     M
35     M
260    M
536    M
      ..
89     B
335    M
218    M
412    B
93     B
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [70]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [71]:
y_train

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [72]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [73]:
X_train_tensor.shape
y_train_tensor.dtype

torch.float32

## Defining the Model

In [74]:
class MyNN(nn.Module):

  # def  __init__(self, X):
  #   self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
  #   self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  # def forward(self, X):
  #   z = torch.matmul(X, self.weights) + self.bias
  #   y_pred = torch.sigmoid(z)
  #   return y_pred

  def forward(self, features):
    out = self.linear(features)
    y_pred = self.sigmoid(out)
    return y_pred

  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   eplsilon = 1e-7;
  #   y_pred = torch.clamp(y_pred, eplsilon, 1-eplsilon)

  #   # Calculate loss
  #   loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
  #   return loss.mean()

### Important Parameters


In [75]:
learning_rate = 0.1
epochs = 25

loss_function = nn.BCELoss()

### Training Pipeline


In [76]:
# create model
model = MyNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(epochs):

  # Forward Bias
  # y_pred = model.forward(X_train_tensor)
  y_pred = model(X_train_tensor.float())

  # Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  optimizer.zero_grad()

  # Backward pass
  loss.backward()

  optimizer.step()

  # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()


  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5572606921195984
Epoch: 2, Loss: 0.545696496963501
Epoch: 3, Loss: 0.5347610712051392
Epoch: 4, Loss: 0.5244083404541016
Epoch: 5, Loss: 0.5145958065986633
Epoch: 6, Loss: 0.5052838921546936
Epoch: 7, Loss: 0.49643635749816895
Epoch: 8, Loss: 0.48801979422569275
Epoch: 9, Loss: 0.48000359535217285
Epoch: 10, Loss: 0.4723598062992096
Epoch: 11, Loss: 0.46506255865097046
Epoch: 12, Loss: 0.4580884873867035
Epoch: 13, Loss: 0.4514159560203552
Epoch: 14, Loss: 0.44502517580986023
Epoch: 15, Loss: 0.43889808654785156
Epoch: 16, Loss: 0.43301790952682495
Epoch: 17, Loss: 0.42736953496932983
Epoch: 18, Loss: 0.42193877696990967
Epoch: 19, Loss: 0.4167126715183258
Epoch: 20, Loss: 0.41167929768562317
Epoch: 21, Loss: 0.4068276286125183
Epoch: 22, Loss: 0.40214741230010986
Epoch: 23, Loss: 0.3976292014122009
Epoch: 24, Loss: 0.39326420426368713
Epoch: 25, Loss: 0.3890443444252014


In [77]:
model.linear.bias

Parameter containing:
tensor([-0.0703], requires_grad=True)

## Evaluation

In [78]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float()) # This will give the values of y_pred from 0 to 1
  y_pred = (y_pred >0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6608186960220337
