In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [ ]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
452       12.000         28.23           76.77      442.5          0.08437   
419       11.160         21.41           70.95      380.3          0.10180   
528       13.940         13.17           90.31      594.2          0.12480   
118       15.780         22.91          105.70      782.6          0.11550   
61         8.598         20.98           54.66      221.8          0.12430   
..           ...           ...             ...        ...              ...   
220       13.650         13.16           87.88      568.9          0.09646   
546       10.320         16.35           65.31      324.9          0.09434   
468       17.600         23.33          119.00      980.5          0.09289   
375       16.170         16.07          106.30      788.5          0.09880   
19        13.540         14.36           87.46      566.3          0.09779   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
452           0.06450        0.040550             0.019450         0.1615   
419           0.05978        0.008955             0.010760         0.1615   
528           0.09755        0.101000             0.066150         0.1976   
118           0.17520        0.213300             0.094790         0.2096   
61            0.08963        0.030000             0.009259         0.1828   
..                ...             ...                  ...            ...   
220           0.08711        0.038880             0.025630         0.1360   
546           0.04994        0.010120             0.005495         0.1885   
468           0.20040        0.213600             0.100200         0.1696   
375           0.14380        0.066510             0.053970         0.1990   
19            0.08129        0.066640             0.047810         0.1885   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
452                 0.06104  ...        13.090          37.88   
419                 0.06144  ...        12.360          28.92   
528                 0.06457  ...        14.620          15.38   
118                 0.07331  ...        20.190          30.50   
61                  0.06757  ...         9.565          27.04   
..                      ...  ...           ...            ...   
220                 0.06344  ...        15.340          16.35   
546                 0.06201  ...        11.250          21.77   
468                 0.07369  ...        21.570          28.87   
375                 0.06572  ...        16.970          19.14   
19                  0.05766  ...        15.110          19.26   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
452            85.07       523.7            0.1208            0.18560   
419            79.26       458.0            0.1282            0.11080   
528            94.52       653.3            0.1394            0.13640   
118           130.30      1272.0            0.1855            0.49250   
61             62.06       273.9            0.1639            0.16980   
..               ...         ...               ...                ...   
220            99.71       706.2            0.1311            0.24740   
546            71.12       384.9            0.1285            0.08842   
468           143.60      1437.0            0.1207            0.47850   
375           113.10       861.5            0.1235            0.25500   
19             99.70       711.2            0.1440            0.17730   

     concavity_worst  concave points_worst  symmetry_worst  \
452          0.18110               0.07116          0.2447   
419          0.03582               0.04306          0.2976   
528          0.15590               0.10150          0.2160   
118          0.73560               0.20340          0.3274   
61           0.09001               0.02778          0.2972   
..               ...                   ...             ...   
220          0.17590               0.08056         

In [ ]:
y_train

452    B
419    B
528    B
118    M
61     B
      ..
220    B
546    B
468    M
375    B
19     B
Name: diagnosis, Length: 455, dtype: object

## Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.62298427,  2.0862857 , -0.64348579, ..., -0.66822679,
        -0.71299659, -0.09280095],
       [-0.86135345,  0.47878867, -0.88322011, ..., -1.09700421,
         0.12416878, -0.70621013],
       [-0.07246498, -1.46340715, -0.08575338, ..., -0.20526924,
        -1.1671865 , -0.63175336],
       ...,
       [ 0.96614358,  0.93133916,  1.09602969, ...,  1.291637  ,
        -0.9440479 ,  2.22452263],
       [ 0.56034844, -0.77986736,  0.57289811, ...,  0.15484276,
         0.40427893,  0.34592121],
       [-0.18597411, -1.18292013, -0.20314905, ...,  0.211301  ,
         0.12575132, -0.6283169 ]])

In [ ]:
y_train

452    B
419    B
528    B
118    M
61     B
      ..
220    B
546    B
468    M
375    B
19     B
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape
y_train_tensor.dtype

torch.float32

## Defining the Model

In [ ]:
class MyNN(nn.Module):

  # def  __init__(self, X):
  #   self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
  #   self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  # def forward(self, X):
  #   z = torch.matmul(X, self.weights) + self.bias
  #   y_pred = torch.sigmoid(z)
  #   return y_pred

  def forward(self, features):
    out = self.linear(features)
    y_pred = self.sigmoid(out)
    return y_pred

  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   eplsilon = 1e-7;
  #   y_pred = torch.clamp(y_pred, eplsilon, 1-eplsilon)

  #   # Calculate loss
  #   loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
  #   return loss.mean()

### Important Parameters


In [ ]:
learning_rate = 0.1
epochs = 25

loss_function = nn.BCELoss()

## Data Loader & DataSet class


In [ ]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
  def __init__(self, data, labels, transform=None):
    self.data = data
    self.labels = labels
    self.transform = transform

  def __len__(self):
    return self.data.shape[0] # Return the total number of samples

  def __getitem__(self, index):
    sample = self.data[index]
    label = self.labels[index]
    if self.transform:
      sample = self.transform(sample) # Apply any transformations if provided
    return sample, label

from torch.utils.data import DataLoader

train_dataset = CustomDataset(X_train_tensor,  y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Training Pipeline


In [1]:
# create model
model = MyNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(epochs):

  for features, labels in train_loader:

    # Forward Bias
    # y_pred = model.forward(X_train_tensor)
    y_pred = model(features)

    # Loss
    loss = loss_function(y_pred, labels.view(-1,1))

    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    optimizer.step()

    # parameters update
    # with torch.no_grad():
    #   model.linear.weight -= learning_rate * model.linear.weight.grad
    #   model.linear.bias -= learning_rate * model.linear.bias.grad

    # zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()

  print(loss.dtype)
  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

NameError: name 'MyNN' is not defined

In [ ]:
model.linear.bias
model.linear.weight

Parameter containing:
tensor([[ 0.4098,  0.1417,  0.2359,  0.2432,  0.1911,  0.0935,  0.3066,  0.2089,
          0.1209, -0.0160,  0.3431, -0.1259,  0.3325,  0.1878,  0.1054, -0.1734,
          0.0374, -0.0279, -0.0090, -0.2197,  0.3363,  0.2366,  0.2720,  0.2559,
          0.0697,  0.1674,  0.2919,  0.3596,  0.0549,  0.1463]],
       requires_grad=True)

## Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float()) # This will give the values of y_pred from 0 to 1
  y_pred = (y_pred >0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5858725905418396
