This notebook contains all relevant functions related to Tensor in PyTorch.

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!" )
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU. ")

GPU not available. Using CPU. 


## Functions in PyTorch

In [ ]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)
# Random numbers between 0 and 1

tensor([[0.8785, 0.1277, 0.5230],
        [0.5595, 0.7629, 0.2807]])

In [ ]:
print(torch.arange(0,10)) # Generates numbers from 0 to 10 with increment of 1
print(torch.arange(0,10,3)) # Generates numbers from 0 to 10 with increment of 3

print(torch.linspace(1,10,10)) # Generates 10 equidistant numbers from 1 to 10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [ ]:
torch.eye(5) # eye is for Identity Matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor Shapes

In [ ]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[2459029315949257070, 7308604897285731189, 8319104481851616290],
        [3756600473238269801, 3258464716185821748, 3919314944490222389]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)
# This will give error if we don't mention the data type explicitly becuase x is of int data type but rand assigns float number from 0 to 1

tensor([[0.3792, 0.1184, 0.8908],
        [0.5249, 0.9299, 0.0257]])

## Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x = x.to(torch.float32)

## Mathematical Operations

### Scalar Operation

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 2
# division
x / 2
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

### Element Wise Operation

In [ ]:

a = torch.rand(2,3);
b = torch.rand(2,3);

print(a)
print(b)

tensor([[0.9063, 0.6598, 0.8157],
        [0.9128, 0.5173, 0.5006]])
tensor([[0.9304, 0.5470, 0.5882],
        [0.6607, 0.9282, 0.4653]])


In [ ]:
 # add
a + b
 # subtract
a - b
 # multiply
a * b
 # divison
a / b
 # power
a ** b
 # mod
a % b

tensor([[0.9063, 0.1127, 0.2275],
        [0.2521, 0.5173, 0.0353]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
c= c % 1.1
print(c)

tensor([1.0000, 0.2000, 0.8000, 0.4000])


In [ ]:
# round
torch.round(c)

tensor([1., 0., 1., 0.])

In [ ]:
torch.ceil(c)

tensor([1., 1., 1., 1.])

In [ ]:
torch.floor(c)

tensor([1., 0., 0., 0.])

In [ ]:
# clamp adjust all the numbers in tensor between the given range
torch.clamp(c, min=2, max=3)
# Here, numbers below 2 will become 2 and numbers more than 3 will become 3

tensor([2., 2., 2., 2.])

## Reduction Operation

In [ ]:
torch.manual_seed(13) # for removing randomization
e = torch.randint(size= (2,3) , low=0, high=10, dtype= torch.float32)
e

tensor([[8., 2., 4.],
        [6., 8., 6.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([14., 20.])

In [ ]:
# mean
torch.mean(e)
# mean along columns
torch.mean(e, dim=0)
# mean along rows
torch.mean(e, dim=1)

tensor([4.6667, 6.6667])

In [ ]:
# median
torch.median(e)
# median along columns
torch.median(e, dim=0)
# median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([4., 6.]),
indices=tensor([2, 2]))

Putting underscore after the functions name make it inplace operation.

## Copying the Tensor

In [ ]:
k= torch.randint(size=(2,3), low =0, high = 10)
k

tensor([[6, 9, 4],
        [8, 7, 6]])

b= k will make the copy of k in b but if k is changed, b will also change becuase they will have same memory location due to assignment operation. To avoid this we use 'clone' function

In [ ]:
b= a.clone()
print(id(a))
print(id(b))

132769065902224
132769066197328


## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.9149, 0.4799, 0.5348],
        [0.2695, 0.2530, 0.3390]])

In [ ]:
# moving the existing tensor to GPU
a = torch.rand((2,3))
a

In [ ]:
b = a.to(device)
b+5

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

## Reshaping Tensors

In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])